MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_RECIPE_NAME = 256

MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FIRSTNAME = 150
MAX_LENGTH_LASTNAME = 150

PAGE_SIZE_QUERY_PARAM = "limit"
PAGE_SIZE = 6
MAX_PAGE_SIZE = 100

RECIPES_LIMIT_QUERY_PARAM = "recipes_limit"
RECIPES_LIMIT_DEFAULT = 100
